#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Aug  2 10:57:45 2019

@author: jiachenlu
"""


import matplotlib.pyplot as plt

def findCo(i):
    x = i % 5
    y = 4 - (i-i%5) / 5
    return x,y

f = open('data.txt')
s1 = 10
s2 = 5
c = 10
f.readline()
plt.show()
while True:
    fig, ax = plt.subplots()
    for i in range(25):
        x,y = findCo(i)
        plt.scatter(x, y, color='red')
        
    line = f.readline()
    line = str(line)
    print(line)
    if line.find('random') != -1:
        c = 'green'
    else:
        c = 'blue'
    start = line.find('{')
    end = line.find('}')
    separator_str = line[start+1:end]
    print(separator_str)
    temp = separator_str.split(',')
    separator = [int(i) for i in temp]
    for i in separator:
        x, y = findCo(i)
        ax.scatter(x, y, color=c)
    plt.show()
f.close()